'use strict';

/**
 * Mints a guest/shopper SLAS access token server-side via the public-client PKCE flow
 * (https://developer.salesforce.com/docs/commerce/commerce-api/guide/slas-public-client).
 *
 * ps_scapiClientId is a public client, so it has no secret and cannot use client_credentials —
 * it must exchange an authorization code obtained via GET .../oauth2/authorize?hint=guest.
 * That exchange is done here (server-side, via dw.net.HTTPClient) rather than in browser JS
 * because reading the authorize redirect's Location header to get the code requires either a
 * same-origin redirect_uri (extra Account Manager setup) or a server-side HTTP client, which
 * isn't subject to the browser's CORS/opaque-redirect restrictions.
 */

var HTTPClient = require('dw/net/HTTPClient');
var MessageDigest = require('dw/crypto/MessageDigest');
var SecureRandom = require('dw/crypto/SecureRandom');
var Encoding = require('dw/crypto/Encoding');
var Bytes = require('dw/util/Bytes');

/**
 * @returns {string} RFC 7636 code_verifier (base64url, no padding)
 */
function generateCodeVerifier() {
    var random = new SecureRandom();
    return Encoding.toBase64URL(random.nextBytes(32));
}

/**
 * @param {string} codeVerifier - the verifier generated by generateCodeVerifier()
 * @returns {string} S256 code_challenge derived from codeVerifier
 */
function generateCodeChallenge(codeVerifier) {
    var digest = new MessageDigest(MessageDigest.DIGEST_SHA_256);
    var hash = digest.digestBytes(new Bytes(codeVerifier, 'UTF-8'));
    return Encoding.toBase64URL(hash);
}

/**
 * @param {string} url - a URL (typically a Location header value)
 * @param {string} param - query parameter name to extract
 * @returns {string|null} the decoded parameter value, or null if not present
 */
function extractQueryParam(url, param) {
    var match = url && url.match(new RegExp('[?&]' + param + '=([^&]*)'));
    return match ? decodeURIComponent(match[1]) : null;
}

/**
 * hint=guest resolves immediately — no real shopper login step — so the authorization code
 * comes back on the redirect's Location header rather than after any user interaction.
 * @param {Object} config - configHelper.getConfig() result
 * @param {string} codeChallenge - S256 code_challenge for this request
 * @returns {string} authorization code
 */
function requestAuthorizationCode(config, codeChallenge) {
    var authorizeUrl = 'https://' + config.shortCode + '.api.commercecloud.salesforce.com'
        + '/shopper/auth/v1/organizations/' + config.organizationId + '/oauth2/authorize'
        + '?client_id=' + encodeURIComponent(config.clientId)
        + '&hint=guest'
        + '&response_type=code'
        + '&redirect_uri=' + encodeURIComponent(config.redirectUri)
        + '&code_challenge=' + encodeURIComponent(codeChallenge);

    var client = new HTTPClient();
    client.setAllowRedirect(false);
    client.open('GET', authorizeUrl);
    client.send();

    var location = client.getResponseHeader('Location');
    var code = extractQueryParam(location, 'code');
    if (!code) {
        throw new Error('SLAS authorize did not return a code (status ' + client.statusCode + '): ' + client.text);
    }
    return code;
}

/**
 * @param {Object} config - configHelper.getConfig() result
 * @param {string} code - authorization code from requestAuthorizationCode()
 * @param {string} codeVerifier - the verifier matching the code_challenge sent to /authorize
 * @returns {Object} parsed SLAS token response (access_token, expires_in, ...)
 */
function requestToken(config, code, codeVerifier) {
    var tokenUrl = 'https://' + config.shortCode + '.api.commercecloud.salesforce.com'
        + '/shopper/auth/v1/organizations/' + config.organizationId + '/oauth2/token';
    var body = 'grant_type=authorization_code_pkce'
        + '&code=' + encodeURIComponent(code)
        + '&code_verifier=' + encodeURIComponent(codeVerifier)
        + '&client_id=' + encodeURIComponent(config.clientId)
        + '&redirect_uri=' + encodeURIComponent(config.redirectUri)
        + '&channel_id=' + encodeURIComponent(config.siteId);

    var client = new HTTPClient();
    client.open('POST', tokenUrl);
    client.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    client.send(body);

    if (client.statusCode !== 200) {
        throw new Error('SLAS token request failed (status ' + client.statusCode + '): ' + client.text);
    }
    return JSON.parse(client.text);
}

/**
 * @param {Object} config - configHelper.getConfig() result; must include shortCode,
 *   organizationId, clientId, siteId, redirectUri
 * @returns {{accessToken: string, expiresIn: number}} the minted guest token and its TTL
 */
function getGuestToken(config) {
    var codeVerifier = generateCodeVerifier();
    var codeChallenge = generateCodeChallenge(codeVerifier);
    var code = requestAuthorizationCode(config, codeChallenge);
    var tokenResponse = requestToken(config, code, codeVerifier);

    return {
        accessToken: tokenResponse.access_token,
        expiresIn: tokenResponse.expires_in
    };
}

module.exports = {
    getGuestToken: getGuestToken
};
